

name: example-basic
on:
  push:
    branches:
      - 'main'
jobs:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v9 and lower ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  basic-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - name: Print new build number
        run: echo "Build number"
